<h1> 파이썬 리스트에서 배열 만들기

In [3]:
import numpy as np
from mpmath import linspace
from numpy.core.numeric import newaxis

In [9]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

<h4>NumPy는 배열의 모든 요소가 같아야한다
<h4>아니라면 상위 타입을 취하게 된다.

In [12]:
np.array([1.2,3,4,5,])

array([1., 2., 3., 4.])

In [13]:
np.array([1,2,3,4], dtype=float)    # 데이터 타입 설정

array([1., 2., 3., 4.])

In [15]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [30]:
# 0으로 채운 길이 10의 정수 배열 만들기
print(np.zeros(10, dtype=int), '\n')

# 1로 채운 3 x 5 부동 소수점 배열 만들기
print(np.ones((3, 5), dtype=float), '\n')

# 3.14로 채운 3 x 5 배열 만들기
print(np.full((3, 5), 3.14), '\n')

# 선형 수열로 채운 배열 만들기
print(np.arange(0, 20, 2), '\n')

# 0과 1사이에 일정한 간격을 가진 다섯 개의 값으로 채운 배열 만들기
print(np.linspace(0, 1, 5), '\n')

# 균등하게 분포된 3 x 3 배열 만들기
print(np.random.random((3, 3)), '\n')

# 정규 분포(평균 0, 표준 편차 = 1)의 난수로 채운 3 x 3 배열 만들기
print(np.random.normal(0, 1, (3, 3)), '\n')

# [0, 10] 구간의 임의의 정수로 채운 3 x 3 배열 만들기
print(np.random.randint(0, 10, (3, 3)), '\n')

# 3 x 3 단위 행렬 만들기
print(np.eye(3), '\n')

[0 0 0 0 0 0 0 0 0 0] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]] 

[ 0  2  4  6  8 10 12 14 16 18] 

[0.   0.25 0.5  0.75 1.  ] 

[[0.49209129 0.28169191 0.71014924]
 [0.20911703 0.22435963 0.49345775]
 [0.78273094 0.16291704 0.20759985]] 

[[ 1.01570668e+00  1.74378749e+00  7.71512904e-01]
 [-3.01438528e-01 -8.81827777e-01  6.90829097e-01]
 [-2.33461852e+00 -6.79566863e-05  4.47392652e-02]] 

[[5 1 3]
 [4 9 8]
 [3 9 2]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



<h1> NumPy 배열 기초

<h3> 배열 속성 지정

In [32]:
np.random.seed(0) # 똑같은 난수 배열이 생성되지 않게 시드 값 설정

x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (3, 4))
x3 = np.random.randint(10, size = (3, 4, 5))

print("x3 ndim: ", x3.ndim) # 차원의 개수
print("x3 shape: ", x3.shape) # 각 차원의 크기
print("x3 size: ", x3.size) # 전체 배열의 크기
print("dtype", x3.dtype) # 각 요소의 타입

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
dtype int64


<h3> 배열 인덱싱 : 단일 요소 접근

In [37]:
print(x1)
print(x1[0])
print(x1[-1], '\n')

print(x2)
print(x2[0, 0])
print(x2[2, -1], '\n')

[5 0 3 3 7 9]
5
9 

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
3
7 



<h3> 배열 슬라이싱 : 하위 배열 접근

<h4> 1차원 하위 배열
<h4> x[start:stop:step]

In [51]:
print(x1)
print(x1[:5]) # 첫 다섯개 요소
print(x1[5:]) # 인덱스 5 다음 요소
print(x1[2:5]) # 중간 하위 배열 
print(x1[::2]) # 2의 배수일때 걸러 구성
print(x1[1::2], '\n') # 인덱스 1에서 시작

print(x1[::-1]) # 모든 요소를 거꾸로 나열
print(x1[5::-2]) # 인덱스 5부터 거꾸로 나열

[5 0 3 3 7 9]
[5 0 3 3 7]
[9]
[3 3 7]
[5 3 7]
[0 3 9] 

[9 7 3 3 0 5]
[9 3 0]


<h4> 다차원 하위 배열

In [56]:
print(x2, '\n')
print(x2[:2, :3], '\n') # 두개의 행 3개의 열
print(x2[:3, ::2], '\n') # 모든 행, 2의 배수 걸러 하나 씩

print(x2[:, 0]) # x2의 첫 번째 열
print(x2[0, :]) # x2의 첫 번째 행

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]] 

[[3 5 2]
 [7 6 8]] 

[[3 2]
 [7 8]
 [1 7]] 

[3 7 1]
[3 5 2 4]


<h3> 배열의 사본 만들기

In [58]:
x2_sub_copy = x2.copy() # x2_sub_copy를 수정해도 원래 배열이 그대로 유지

x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

<h1> 배열 재구조화

In [59]:
grid = np.arange(1, 10).reshape(3, 3)   # 이 코드가 동작하려면 배열의 규모가 형상이 변경된 배열의 규모와 일치해야한다.
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
# 두 가지 배열 재구조 방식

# reshape을 이용한 행 벡터
x = np.array([1, 2, 3, 4, 5])
print(x.reshape(1, 5))
# newaxis를 이용한 행 벡터
print(x[np.newaxis, :], '\n')

# reshape을 이용한 열 벡터
x = np.array([1, 2, 3, 4, 5])
print(x.reshape(5, 1))

# newaxis를 이용한 열 벡터
print(x[:, np.newaxis])

[[1 2 3 4 5]]
[[1 2 3 4 5]] 

[[1]
 [2]
 [3]
 [4]
 [5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


<h1> 배열 연결 및 분할

<h3> 배열 연결

In [64]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([100,101,102,103,104])

np.concatenate((x, y)) # 2 차원 배열도 가능하다

array([  1,   2,   3,   4,   5, 100, 101, 102, 103, 104])

In [80]:
x = np.array([1, 2, 3])
grid = np.arange(1,7).reshape(2, 3)

print(np.vstack([x, grid]), '\n') # 혼합된 차원의 배열은 np.vstack(수직 스택)이 명확하다.

y = np.array([[99], [200]])
print(np.hstack([grid, y])) # 혼합된 차원의 배열은 np.hstack(수평 스택)이 명확하다.


[[1 2 3]
 [1 2 3]
 [4 5 6]] 

[[  1   2   3  99]
 [  4   5   6 200]]


<h3> 배열 분할

In [85]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])

x1,x2,x3

(array([1, 2, 3]), array([99, 99]), array([3, 2, 1]))

In [94]:
grid = np.arange(16).reshape((4,4))

upper, lower = np.vsplit(grid, [2])

print(grid,'\n')
print(upper,'\n')
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[0 1 2 3]
 [4 5 6 7]] 

[[ 8  9 10 11]
 [12 13 14 15]]


In [95]:
grid = np.arange(16).reshape((4,4))

left, right = np.hsplit(grid, [2])

print(grid,'\n')
print(left,'\n')
print(right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
